apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/madb0o/cve
    newTag: latest
    digest: sha256:fc92e02bd5ac465b3d973dd8114148845b263e1f464eb7abf8952132b8697d8d
