apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/madb0o/cve
    newTag: latest
    digest: sha256:60e5e575620f282c34d886b47ab07724d520647ac9317cab242fc6bbd93f3dd7
