apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/madb0o/cve
    newTag: latest
    digest: sha256:d3cdc7d22efc26cdc770ea0661625742562b1b208371f6c651b26f1aaa1ab56b
